from os import path
import subprocess

current_dir = path.abspath('.')
build_dir = path.abspath(path.join(current_dir, '..', 'build'))

webgl = File(path.join(build_dir, 'libWebGL.a'))
spidermonkey_src = path.abspath(path.join(current_dir, '..', 'deps', 'spidermonkey', 'js', 'src'))
spidermonkey = File(path.join(spidermonkey_src, 'libjs_static.a'))
spidermonkey_includes = spidermonkey_src

glfw_src = path.abspath(path.join(current_dir, '..', 'deps', 'glfw', ))
glfw = File(path.join(glfw_src, 'lib', 'cocoa', 'libglfw.a'))
glfw_includes = path.abspath(path.join(glfw_src, 'include'))


FRAMEWORKS = ['OpenGL', 'Cocoa']

# Configure spidermonkey
if not path.isfile(path.join(spidermonkey_src, 'Makefile')):
  spidermonkey_configure = [path.join(spidermonkey_src, 'configure'),'--disable-shared-js']
  subprocess.call(spidermonkey_configure, cwd=spidermonkey_src)

# Make spidermonkey
spidermonkey_make = ['make', '-f', path.join(spidermonkey_src, 'Makefile')]
subprocess.call(spidermonkey_make, cwd=spidermonkey_src)

# Make webgljs
env = Environment(CPPPATH=[spidermonkey_includes, path.join(current_dir, '..', 'include'), glfw_includes])
env.Program('webgljs', Glob('js/*.cc'),
  LIBS = [webgl, spidermonkey, glfw],
  FRAMEWORKS = FRAMEWORKS
  )